/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayPreviewRouteImport } from './routes/today-preview'
import { Route as SundayCheckinRouteImport } from './routes/sunday-checkin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServeApplyRouteImport } from './routes/serve-apply'
import { Route as RetreatRegisterRouteImport } from './routes/retreat-register'
import { Route as RetreatAdminRouteImport } from './routes/retreat-admin'
import { Route as RetreatRouteImport } from './routes/retreat'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MessageBoardRouteImport } from './routes/message-board'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FellowshipCheckinRouteImport } from './routes/fellowship-checkin'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DataPreviewRouteImport } from './routes/data-preview'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayPublicTokenRouteImport } from './routes/today-public.$token'

const TodayPreviewRoute = TodayPreviewRouteImport.update({
  id: '/today-preview',
  path: '/today-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayCheckinRoute = SundayCheckinRouteImport.update({
  id: '/sunday-checkin',
  path: '/sunday-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeApplyRoute = ServeApplyRouteImport.update({
  id: '/serve-apply',
  path: '/serve-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatRegisterRoute = RetreatRegisterRouteImport.update({
  id: '/retreat-register',
  path: '/retreat-register',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatAdminRoute = RetreatAdminRouteImport.update({
  id: '/retreat-admin',
  path: '/retreat-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatRoute = RetreatRouteImport.update({
  id: '/retreat',
  path: '/retreat',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageBoardRoute = MessageBoardRouteImport.update({
  id: '/message-board',
  path: '/message-board',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipCheckinRoute = FellowshipCheckinRouteImport.update({
  id: '/fellowship-checkin',
  path: '/fellowship-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPreviewRoute = DataPreviewRouteImport.update({
  id: '/data-preview',
  path: '/data-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayPublicTokenRoute = TodayPublicTokenRouteImport.update({
  id: '/today-public/$token',
  path: '/today-public/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data-preview': typeof DataPreviewRoute
  '/feedback': typeof FeedbackRoute
  '/fellowship-checkin': typeof FellowshipCheckinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retreat': typeof RetreatRoute
  '/retreat-admin': typeof RetreatAdminRoute
  '/retreat-register': typeof RetreatRegisterRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signup': typeof SignupRoute
  '/sunday-checkin': typeof SundayCheckinRoute
  '/today-preview': typeof TodayPreviewRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data-preview': typeof DataPreviewRoute
  '/feedback': typeof FeedbackRoute
  '/fellowship-checkin': typeof FellowshipCheckinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retreat': typeof RetreatRoute
  '/retreat-admin': typeof RetreatAdminRoute
  '/retreat-register': typeof RetreatRegisterRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signup': typeof SignupRoute
  '/sunday-checkin': typeof SundayCheckinRoute
  '/today-preview': typeof TodayPreviewRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data-preview': typeof DataPreviewRoute
  '/feedback': typeof FeedbackRoute
  '/fellowship-checkin': typeof FellowshipCheckinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retreat': typeof RetreatRoute
  '/retreat-admin': typeof RetreatAdminRoute
  '/retreat-register': typeof RetreatRegisterRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signup': typeof SignupRoute
  '/sunday-checkin': typeof SundayCheckinRoute
  '/today-preview': typeof TodayPreviewRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/data-preview'
    | '/feedback'
    | '/fellowship-checkin'
    | '/forgot-password'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/retreat'
    | '/retreat-admin'
    | '/retreat-register'
    | '/serve-apply'
    | '/signup'
    | '/sunday-checkin'
    | '/today-preview'
    | '/today-public/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/data-preview'
    | '/feedback'
    | '/fellowship-checkin'
    | '/forgot-password'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/retreat'
    | '/retreat-admin'
    | '/retreat-register'
    | '/serve-apply'
    | '/signup'
    | '/sunday-checkin'
    | '/today-preview'
    | '/today-public/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/data-preview'
    | '/feedback'
    | '/fellowship-checkin'
    | '/forgot-password'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/retreat'
    | '/retreat-admin'
    | '/retreat-register'
    | '/serve-apply'
    | '/signup'
    | '/sunday-checkin'
    | '/today-preview'
    | '/today-public/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DataPreviewRoute: typeof DataPreviewRoute
  FeedbackRoute: typeof FeedbackRoute
  FellowshipCheckinRoute: typeof FellowshipCheckinRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessageBoardRoute: typeof MessageBoardRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RetreatRoute: typeof RetreatRoute
  RetreatAdminRoute: typeof RetreatAdminRoute
  RetreatRegisterRoute: typeof RetreatRegisterRoute
  ServeApplyRoute: typeof ServeApplyRoute
  SignupRoute: typeof SignupRoute
  SundayCheckinRoute: typeof SundayCheckinRoute
  TodayPreviewRoute: typeof TodayPreviewRoute
  TodayPublicTokenRoute: typeof TodayPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today-preview': {
      id: '/today-preview'
      path: '/today-preview'
      fullPath: '/today-preview'
      preLoaderRoute: typeof TodayPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-checkin': {
      id: '/sunday-checkin'
      path: '/sunday-checkin'
      fullPath: '/sunday-checkin'
      preLoaderRoute: typeof SundayCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve-apply': {
      id: '/serve-apply'
      path: '/serve-apply'
      fullPath: '/serve-apply'
      preLoaderRoute: typeof ServeApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-register': {
      id: '/retreat-register'
      path: '/retreat-register'
      fullPath: '/retreat-register'
      preLoaderRoute: typeof RetreatRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-admin': {
      id: '/retreat-admin'
      path: '/retreat-admin'
      fullPath: '/retreat-admin'
      preLoaderRoute: typeof RetreatAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat': {
      id: '/retreat'
      path: '/retreat'
      fullPath: '/retreat'
      preLoaderRoute: typeof RetreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-board': {
      id: '/message-board'
      path: '/message-board'
      fullPath: '/message-board'
      preLoaderRoute: typeof MessageBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship-checkin': {
      id: '/fellowship-checkin'
      path: '/fellowship-checkin'
      fullPath: '/fellowship-checkin'
      preLoaderRoute: typeof FellowshipCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-preview': {
      id: '/data-preview'
      path: '/data-preview'
      fullPath: '/data-preview'
      preLoaderRoute: typeof DataPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today-public/$token': {
      id: '/today-public/$token'
      path: '/today-public/$token'
      fullPath: '/today-public/$token'
      preLoaderRoute: typeof TodayPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DataPreviewRoute: DataPreviewRoute,
  FeedbackRoute: FeedbackRoute,
  FellowshipCheckinRoute: FellowshipCheckinRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessageBoardRoute: MessageBoardRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RetreatRoute: RetreatRoute,
  RetreatAdminRoute: RetreatAdminRoute,
  RetreatRegisterRoute: RetreatRegisterRoute,
  ServeApplyRoute: ServeApplyRoute,
  SignupRoute: SignupRoute,
  SundayCheckinRoute: SundayCheckinRoute,
  TodayPreviewRoute: TodayPreviewRoute,
  TodayPublicTokenRoute: TodayPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
