/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayPreviewRouteImport } from './routes/today-preview'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServeApplyRouteImport } from './routes/serve-apply'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MessageBoardRouteImport } from './routes/message-board'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DataPreviewRouteImport } from './routes/data-preview'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayPublicTokenRouteImport } from './routes/today-public.$token'

const TodayPreviewRoute = TodayPreviewRouteImport.update({
  id: '/today-preview',
  path: '/today-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeApplyRoute = ServeApplyRouteImport.update({
  id: '/serve-apply',
  path: '/serve-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageBoardRoute = MessageBoardRouteImport.update({
  id: '/message-board',
  path: '/message-board',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPreviewRoute = DataPreviewRouteImport.update({
  id: '/data-preview',
  path: '/data-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayPublicTokenRoute = TodayPublicTokenRouteImport.update({
  id: '/today-public/$token',
  path: '/today-public/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data-preview': typeof DataPreviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signup': typeof SignupRoute
  '/today-preview': typeof TodayPreviewRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data-preview': typeof DataPreviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signup': typeof SignupRoute
  '/today-preview': typeof TodayPreviewRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/data-preview': typeof DataPreviewRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signup': typeof SignupRoute
  '/today-preview': typeof TodayPreviewRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/data-preview'
    | '/forgot-password'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/serve-apply'
    | '/signup'
    | '/today-preview'
    | '/today-public/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/data-preview'
    | '/forgot-password'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/serve-apply'
    | '/signup'
    | '/today-preview'
    | '/today-public/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/data-preview'
    | '/forgot-password'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/serve-apply'
    | '/signup'
    | '/today-preview'
    | '/today-public/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DataPreviewRoute: typeof DataPreviewRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessageBoardRoute: typeof MessageBoardRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServeApplyRoute: typeof ServeApplyRoute
  SignupRoute: typeof SignupRoute
  TodayPreviewRoute: typeof TodayPreviewRoute
  TodayPublicTokenRoute: typeof TodayPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today-preview': {
      id: '/today-preview'
      path: '/today-preview'
      fullPath: '/today-preview'
      preLoaderRoute: typeof TodayPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve-apply': {
      id: '/serve-apply'
      path: '/serve-apply'
      fullPath: '/serve-apply'
      preLoaderRoute: typeof ServeApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-board': {
      id: '/message-board'
      path: '/message-board'
      fullPath: '/message-board'
      preLoaderRoute: typeof MessageBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-preview': {
      id: '/data-preview'
      path: '/data-preview'
      fullPath: '/data-preview'
      preLoaderRoute: typeof DataPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today-public/$token': {
      id: '/today-public/$token'
      path: '/today-public/$token'
      fullPath: '/today-public/$token'
      preLoaderRoute: typeof TodayPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DataPreviewRoute: DataPreviewRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessageBoardRoute: MessageBoardRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServeApplyRoute: ServeApplyRoute,
  SignupRoute: SignupRoute,
  TodayPreviewRoute: TodayPreviewRoute,
  TodayPublicTokenRoute: TodayPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
